#-------------------------------------------------------------------------------------------------------------
# Copyright (c) lingmei tech taobao. All rights reserved.
#-------------------------------------------------------------------------------------------------------------

FROM registry.cn-hangzhou.aliyuncs.com/lingmeixyz/photon-activity-dev:dev

